import './globals.css'
import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import GlobalState from '@/contex'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
        <div className='main'>
          <div className='gradient' />
        </div>

        <main className='app'>
          <Navbar />
          {children}
        </main>
        </GlobalState>
      </body>
    </html>
  )
}
